"""
Created on Wed Nov 26 2025
Last Update on Fri Nov 28 2025
@project ScaleAgData
@author: paolo cosmo silvestro
This script merges multiple CSV files located inside a given folder into a single
output CSV file. It automatically identifies all .csv files in the directory,
reads them, adds an additional column named 'AOI' to each one, and concatenates
them into a single DataFrame.

The value of the 'AOI' column is derived from the first three characters of the
original CSV filename (excluding the extension). This provides a simple and
automatic way to track the origin or geographic area associated with each CSV.

INPUT:
    - input_path (str):
        Path to a folder containing one or more CSV files to merge.
        Only files with the .csv extension are processed.

    - output_filename (str):
        Name of the merged CSV file to be created (including extension, e.g.
        'merged_output.csv').

OUTPUT:
    - A single CSV file saved in the same input directory. It contains:
        * All rows from all processed CSV files.
        * An added first column 'AOI' indicating the first three letters of
          each original filename.
        * Columns preserved in their original order.
        * No index column.

ADDITIONAL NOTES:
    - If no CSV files are found or processed, the script prints a warning and
      terminates without creating an output file.
    - Any CSV that cannot be read due to errors is skipped, and a message is
      displayed.

This script is intended to support the consolidation of tabular outputs 
generated by other components of the ScaleAgData Grassaland Rilab  workflow.
"""

import pandas as pd
import os
from typing import List

def merge_csv_with_aoi(input_path: str, output_filename: str) -> None:
    """
    Identifies all .csv files in a given directory path, merges them into a 
    single DataFrame, adds an initial column named 'AOI' containing the first 
    three letters of the original CSV filename, and saves the result.

    Args:
        input_path (str): The path to the folder containing the CSV files.
        output_filename (str): The name (including .csv) of the output file.
    """
    
    # List to store DataFrames from all files
    list_of_dfs: List[pd.DataFrame] = []
    
    print(f"Searching for CSV files in: {input_path}")
    
    # Iterate over all files in the specified path
    for filename in os.listdir(input_path):
        if filename.endswith('.csv'):
            
            # 1) Identify CSV files
            full_file_path = os.path.join(input_path, filename)
            print(f"Found and processing: {filename}")
            
            try:
                # Load the CSV file into a DataFrame
                df = pd.read_csv(full_file_path)
                
                # Extract the first three letters of the filename (excluding extension)
                name_without_extension = os.path.splitext(filename)[0]
                
                # Take the first three letters (or the whole name if shorter)
                aoi_value = name_without_extension[:3]
                
                # 2) Add the initial 'AOI' column
                # Inserts the column at position 0 (the first column)
                df.insert(0, 'AOI', aoi_value)
                
                list_of_dfs.append(df)
                
            except Exception as e:
                print(f"Error reading or processing {filename}: {e}")
                
    
    if not list_of_dfs:
        print("No CSV files found or processed. Operation cancelled.")
        return
        
    # Merge all DataFrames
    merged_df = pd.concat(list_of_dfs, ignore_index=True)
    
    # 3) Save the final CSV
    output_path = os.path.join(input_path, output_filename)
    merged_df.to_csv(output_path, index=False)
    
    print("-" * 50)
    print(f"Merge completed successfully!")
    print(f"File saved as: {output_path}")
    print(f"Total rows in the merged file: {len(merged_df)}")
